version: '3.8'

services:
  web:
    build: .
    depends_on:
      - db
    ports:
      - '5000:5000'
    volumes:
         - ./uploads:/app/uploads
         - ./:/app
    environment:
      FLASK_DEBUG: "on"
      FLASK_APP: ./app.py
  
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=quiz
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"

volumes:
  db:
    driver: local

